quota/course/urls.py
from django.urls import path

from . import views

app_name = 'course'
urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.add, name='add'),
    path('remove/<int:request_id>', views.remove, name='remove'),
]

quota/hello/urls.py
from django.urls import path

from . import views

app_name = 'hello'
urlpatterns = [
    path('', views.index, name='index'),
]

quota/quota/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('course/', include('course.urls', namespace='course')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('hello.urls', namespace='hello')),
]

quota/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

quota/course/models.py
from pickle import FALSE
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User

# Create your models here.

class ID(models.Model):
    code = models.CharField(max_length=5)
    coursename = models.CharField(max_length=100)

    def __str__(self):
        return f"{ self.code }({ self.coursename })"

class Course(models.Model):
    # subject (link to class ID)
    subject = models.ForeignKey(ID, on_delete=models.CASCADE, related_name="CourseCode")
    
    # semester
    class SemesterStatus(models.IntegerChoices):
        semester_one = 1
        semester_two = 2
        summer = 3
    semester = models.PositiveIntegerField(choices=SemesterStatus.choices)
    
    # year
    year  = models.CharField(max_length=4, help_text="Use format: YYYY")
    
    # seat
    seat  = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(9999)])

    # status: open/ close
    class CStatus(models.IntegerChoices):
        open = 1
        close = 0
    coursestatus = models.IntegerField(choices=CStatus.choices)

    def __str__(self):
        return f"{ self.subject }: semester{ self.semester } year{ self.year }: seat quota[{ self.seat }]: { self.coursestatus })"
    
    def is_seat_available(self):
        return self.students.count() < self.seat

class Request(models.Model):
    username = models.ForeignKey(User, on_delete=models.PROTECT, db_constraint=False, related_name="User")
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, related_name="students", blank=True, null=True)

    def __str__(self):
        return f"{ self.username }: course{ self.course.subject } { self.course.semester }/{ self.course.year }"

quota/hello/models.py
from django.db import models

# Create your models here.

quota/users/models.py
from django.db import models

# Create your models here.

quota/course/views.py
from django.shortcuts import render
from .models import ID, Course, Request
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.contrib.auth.models import User

# Create your views here.
def index(request):
    course_exclude = Request.objects
    course = course_exclude.filter(username=request.user.id)
    check_course = Course.objects.exclude(subject__in=[i.course.id for i in course]).exclude(coursestatus=0)
    data = []
    
    for i in check_course:
        seat = Request.objects.filter(course=i.id)
        if len(seat) < i.seat:
            data.append(i)

    return render(request, 'course/index.html', {
        'course': course,
        'noncourse': data
    })

def add(request):
    if request.method == "POST":
        courseId = request.POST["course"]
        course = Course.objects.get(pk=courseId)
        seat = Request.objects.filter(course=course.id)
        seatUNavailable = len(seat)

        is_registered = Request.objects.filter(username=request.user.id).filter(course=course.id)
        if len(is_registered) > 0:
            return HttpResponse('You had been requested.')

        if seatUNavailable >= course.seat:
            return HttpResponse('Seat is full.')
        
        if course.coursestatus == 0:
            return HttpResponse('Course is closed.')
            
        Request.objects.create(username_id=request.user.id, course_id=course.subject.id)
    return HttpResponseRedirect(reverse('course:index'))

def remove(request, request_id):
    course_id = Request.objects.get(pk=request_id).course.id
    courses = Request.objects.filter(username=request.user.id)
    course = Course.objects.get(pk=course_id)
    check = 0

    for i in courses:
        if course_id == i.course.id:
            check+= 1
    
    if check == 0:
        return HttpResponse('You had not requested.')
    
    Request.objects.filter(username=request.user.id).filter(course=course.id).delete()
    
    return HttpResponseRedirect(reverse('course:index'))

quota/hello/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'hello/index.html')

quota/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    return render(request, 'users/index.html')

def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'you are logged out.'
    })

quota/course/templates/course/index.html
{% extends 'course/layout.html' %}
{% block body %}

<div id="box">
    <h1>Request Course</h1>
    <br>
    <form action="{% url 'course:add' %}" method="post">
        {% csrf_token %}
        {% if noncourse|length == 0 %}
        <i>No course :(</i>
        {% else %}
        <select name="course">
            {% for course in noncourse %}
            <option value="{{ course.id }}">{{ course.subject }} year{{ course.semester }}/{{ course.year }}</option>
            {% endfor %}
        </select>
        <br>
        <input type="submit" value="Request Course">
        {% endif %}
    </form>
</div>

<div id="box">
    <h1>Course List</h1>
    <ul>
        {% for courses in course %}
        <li>{{ courses.course.subject }} year{{ courses.course.semester }}/{{ courses.course.year }}
            <a href="{% url 'course:remove' courses.id %}"><button class="buttonremove">Remove</button></a>
        </li>
        {% empty %}
        <li>No course</li>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'users:index' %}"><button class="button">Go to Profile</button></a>
{% endblock %}

quota/course/templates/course/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Course</title>
        <link href="{% static 'course/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

quota/hello/templates/hello/index.html
{% extends 'hello/layout.html' %}
{% block body %}

<div id="box">
    <h1>Quota System Login Page</h1>
    <table class="container">
        <tr>
            <td>
                <a href="{% url 'users:login' %}">
                    <button class="button">User</button>
                </a>
            </td>
            <td>
                <a href="{% url 'admin:index' %}">
                    <button class="button">Admin</button>
                </a>
            </td>
        </tr>
    </table>  
</div>

{% endblock %}

quota/hello/templates/hello/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Quota System Login Page</title>
        <link href="{% static 'hello/css/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

quota/users/templates/users/index.html
{% extends 'users/layoutwelcome.html' %}
{% block body %}

<div id="box1">
    <h1>Welcome, {{ request.user.first_name }}</h1>
</div>

<div id="box2">
    <table class="container">
        <tr>
            <td>
                <ul>
                Username: {{ request.user.username }}
                <br>
                Email: {{ request.user.email }}
                </ul>
            </td>
            <td>
                <a href="{% url 'course:index' %}"><button class="button">Course</button></a>
                <br>
                <a href="{% url 'users:logout' %}"><button class="button">Logout</button></a>
            </td>
        </tr>
    </table>
</div>
{% endblock %}

quota/users/templates/users/layoutlogin.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Login</title>
        <link href="{% static 'users/css/styleslogin.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

quota/users/templates/users/layoutwelcome.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Welcome!</title>
        <link href="{% static 'users/css/styleswelcome.css' %}" rel="stylesheet">
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

quota/users/templates/users/login.html
{% extends 'users/layoutlogin.html' %}
{% block body %}

<div id="box">

    <h1>Login Student</h1>

    {% if message %}
        <div style="color: red">{{ message }}</div>
    {% endif %}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <br>
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'hello:index' %}"><p>Go to Homepage</p></a>

</div>

{% endblock %}